### ISSUE TITLE
Add Server ... "Network error: SSL handshake failed"

### ISSUE THREAD

**Issue by madworm** [drawpile/dpserver#1]
I've installed the dpserver as per howto on the website in a VM.

Firewall is open for ports 27750, 80, 443.

Joining a session works, but adding the server to the list fails with SSL handshake error.

**Comment by callaa** [comment]
Most likely the problem is a self signed certificate. The setup script uses a self signed cert by default, which Drawpile client apparently doesn't accept. I think it might be possible to add support for explicitly accepting the certificate to the client. If you have a domain name for your server, you can enable Let's Encrypt to get a valid certificate.

**Comment by madworm** [comment]
I was just running an internal test vm to evaluate if we have any use for it in teaching, so I didn't bother with any public dns names and so forth.

**Comment by notfood** [comment]
It was required to run `certbot` to allow SSL to work without warnings of self-signed certificate. Script already handles it now.
